package xyz.sattar.javid.proqueue.feature.createVisitor

import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flow
import xyz.sattar.javid.proqueue.core.ui.BaseViewModel
import xyz.sattar.javid.proqueue.domain.model.Visitor
import xyz.sattar.javid.proqueue.domain.usecase.VisitorUpsertUseCase

class CreateVisitorViewModel(
    initialState: CreateVisitorState,
    private val visitorUpsertUseCase: VisitorUpsertUseCase
) : BaseViewModel<CreateVisitorState, CreateVisitorState.PartialState, CreateVisitorEvent, CreateVisitorIntent>(
    initialState
) {
    override fun handleIntent(intent: CreateVisitorIntent): Flow<CreateVisitorState.PartialState> {
        return when (intent) {
            is CreateVisitorIntent.CreateVisitor -> createVisitor(
                intent.fullName,
                intent.phoneNumber
            )
            
            CreateVisitorIntent.BackPress -> {
                sendEvent(CreateVisitorEvent.BackPressed)
            }
        }
    }

    override fun reduceState(
        currentState: CreateVisitorState,
        partialState: CreateVisitorState.PartialState
    ): CreateVisitorState {
        return when (partialState) {
            CreateVisitorState.PartialState.VisitorCreated ->
                currentState.copy(visitorCreated = true, isLoading = false, message = null)

            is CreateVisitorState.PartialState.IsLoading ->
                currentState.copy(visitorCreated = false, isLoading = true, message = null)

            is CreateVisitorState.PartialState.ShowMessage ->
                currentState.copy(
                    visitorCreated = false,
                    isLoading = false,
                    message = partialState.message
                )
        }
    }

    override fun createErrorState(message: String): CreateVisitorState.PartialState =
        CreateVisitorState.PartialState.ShowMessage(message)

    private fun createVisitor(
        fullName: String,
        phoneNumber: String
    ): Flow<CreateVisitorState.PartialState> = flow {
        emit(CreateVisitorState.PartialState.IsLoading(true))
        
        val currentTime = 0L
        val visitorId = visitorUpsertUseCase.invoke(
            Visitor(
                id = 0, // Auto-generated by Room
                fullName = fullName,
                phoneNumber = phoneNumber,
                createdAt = currentTime
            )
        )
        
        emit(CreateVisitorState.PartialState.VisitorCreated)
        if (visitorId != -1L) {
            sendEvent(CreateVisitorEvent.VisitorCreated(visitorId))
        } else {
            emit(CreateVisitorState.PartialState.ShowMessage("خطا در ایجاد مراجع"))
        }
    }
}
