package xyz.sattar.javid.proqueue.domain.usecase

import xyz.sattar.javid.proqueue.domain.AppointmentRepository
import xyz.sattar.javid.proqueue.domain.model.Appointment
import kotlin.time.Clock
import kotlin.time.ExperimentalTime

class CreateAppointmentUseCase(private val repository: AppointmentRepository) {
    @OptIn(ExperimentalTime::class)
    suspend operator fun invoke(
        businessId: Long,
        visitorId: Long,
        appointmentDate: Long,
        serviceDuration: Int?
    ): Boolean {
        val now = Clock.System.now().toEpochMilliseconds()
        val appointment = Appointment(
            id = 0, // Auto-generated by Room
            businessId = businessId,
            visitorId = visitorId,
            appointmentDate = appointmentDate,
            serviceDuration = serviceDuration,
            status = "WAITING",
            createdAt = now,
            updatedAt = now
        )
        return repository.createAppointment(appointment)
    }
}
